name: Python Package using Conda

on: 
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        sudo apt -y install ghostscript imagemagick tar zip
    - name: Create Quartets Set
      run: |
        cd quartett
        python3 ./create_set.py
        cd ..
    - name: Convert PDF to set of images
      run: |
        cd quartett
        gs -dNOPAUSE -dBATCH -sDEVICE=png16m -dTextAlphaBits=4 -r300 -sOutputFile="card-%04d.png" quartett.pdf
        tar czf quartett_images.tar.gz card-*.png
        zip quartett_images.zip card-*.png
        cd ..
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: Quartets PDF
        # Destination path
        path: /home/runner/work/card-games/card-games/quartett/quartett.pdf
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: Quartets Images TGZ
        # Destination path
        path: /home/runner/work/card-games/card-games/quartett/quartett_images.tar.gz
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: Quartets Images ZIP
        # Destination path
        path: /home/runner/work/card-games/card-games/quartett/quartett_images.zip
