name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        sudo apt -y install ghostscript
    - name: Create Quartets Set
      run: |
        cd quartett
        python3 ./create_set.py
        cd ..
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: Quartets PDF
        # Destination path
        path: /home/runner/work/card-games/card-games/quartett/quartett.pdf
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "quartett/quartett.pdf"
        token: ${{ secrets.GITHUB_TOKEN }}
